### PR TITLE
fix: context with symbols

### LINKED ISSUE #93: ESlint output no errors or warnings when directory path includes square brackets
- Operating System: Windows 10
- Node Version: v14.16.0
- NPM Version: 7.6.3
- webpack Version: 5.28.0
- eslint-webpack-plugin Version: 2.5.3

### Expected Behavior
Show errors and warnings

### Actual Behavior
Nothing happens

### Code

[Link to code to test](https://github.com/ZiiMs/eslint-webpack-example)

### How Do We Reproduce?
The code I provided above should suffice, has two errors and a warning in src/containers/App/index.js

All you have to do is put the project in a folder that's path includes square brackets E.G

S:\Servers\CTest\txData\CFXDefault_2A8AD9.base\resources\ **_[ziim]_** \ziim-progress\progress.client\html

If I drag my project one folder down from **_[ziim]_** it has linting, drag it one folder up it breaks again. Tried it with multiple projects.

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #93 

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
We use this in `copy-webpack-plugin` https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L168, maybe we can copy/paste logic from `fast-glob` here

File: src/utils.js [hunk 1]
```diff
@@ -1,22 +1,17 @@
...
  */
 export function parseFiles(files, context) {
-  return arrify(files).map(
-    (/** @type {string} */ file) =>
-      `${replaceBackslashes(context).replace(
-        UNESCAPED_GLOB_SYMBOLS_RE,
-        '\\$2'
-      )}/${replaceBackslashes(file)}`
+  return arrify(files).map((/** @type {string} */ file) =>
+    replaceBackslashes(join(context, file))
```
Comment (alexander-akait) [inline src/utils.js:14]: Glob should always have `/`

Comment (ricardogobbosouza) [reply src/utils.js:14]: In fact it was like this, they may not work when we have a folder like the test `[symbols]`.
I'm taking the regex out of context, because it doesn't really make sense

https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/src/utils.js#L6
https://github.com/mrmlnc/fast-glob/blob/master/src/utils/path.ts#L6

Comment (alexander-akait) [reply src/utils.js:14]: :+1:

Comment (ricardogobbosouza) [reply src/utils.js:14]: This does not apply here

**Review by alexander-akait — APPROVED** [review]
