### PR TITLE
fix: threads multi-compiler

### LINKED ISSUE #56: 'threads' doesn't compatiable with webpack multi-compiler
- Operating System: macOS
- Node Version: 12.14.0
- NPM Version: 6.13.4 (yarn 1.22.10)
- webpack Version: 4.44.2/webpack@5
- eslint-webpack-plugin Version: 2.4.1

Thanks to the contributors of this plugin, it solves many pain points of `eslint-loader`. 

We are using webpack to output different type of bundle through multi-compiler. If setting threads of `eslint-webpack-plugin`, the output will be incomplete.  So it's not recommended to use this option with webpack multi-compiler?
Or it can be fixed in webpack? The result of webpack@4 and webpack@5 is similar.

### Expected Behavior

bundle output should be
```
dist
├── desktop.js
└── mobile.js
```
### Actual Behavior

bundle output is incomplete
```
dist
├── desktop.js

```

#### webpack@4.44.2 and eslint-webpack-plugin@2.4.1 with threads
bundle output: incomplete
console output
```
[webpack-cli] Compilation finished
✨  Done in 2.93s.
```

Some of our  project's tests are based on the output of webpack. So the incomplete console output let the tests fail after bumping the version of `eslint-webpack-plugin` to 2.4.1.

#### webpack@4.44.2 and eslint-webpack-plugin@2.4.0 with threads
bundle output: **High probability** incomplete, Small probability complete(according to the test of reproducible repo)
console output
```
[webpack-cli] Compilation finished
[webpack-cli] Compilation finished
Hash: d3616dbfeab31a03f79ed3616dbfeab31a03f79e
Version: webpack 4.44.2
Child mobile:
    Hash: d3616dbfeab31a03f79e
    Time: 508ms
    Built at: 12/02/2020 5:04:22 AM
        Asset        Size  Chunks             Chunk Names
    mobile.js  1010 bytes       0  [emitted]  main
    Entrypoint main = mobile.js
    [0] ./src/index.js 38 bytes {0} [built]
Child desktop:
    Hash: d3616dbfeab31a03f79e
    Time: 537ms
    Built at: 12/02/2020 5:04:22 AM
         Asset        Size  Chunks             Chunk Names
    desktop.js  1010 bytes       0  [emitted]  main
    Entrypoint main = desktop.js
    [0] ./src/index.js 38 bytes {0} [built]
✨  Done in 2.12s.
```

### How Do We Reproduce?
[Reproducible repo](https://github.com/fangbinwei/eslint-webpack-plugin-issue-56)

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Resolve #56

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -17,6 +17,7 @@ export class ESLintWebpackPlugin {
    * @param {Options} options
    */
   constructor(options = {}) {
+    this.key = Math.random().toString();
```
Comment (alexander-akait) [inline src/index.js:20]: Bad idea, you need set `key` in `apply`, use `compiler.name` as prefix, if it is `undefined` use `unknown`, if the next compiler also doesn't `name` use `unknown_1` and etc

Comment (ricardogobbosouza) [reply src/index.js]: ok

Comment (ricardogobbosouza) [reply src/index.js]: Updated @alexander-akait

**Review by alexander-akait — APPROVED** [review]
