### PR TITLE
fix: child compiler lint

### LINKED ISSUE #125: plugin does not lint the files from child compiler
### Bug report

plugin does not lint the files from child compiler. If I use eslint-loader, it will lint the files from child compiler.

### Actual Behavior

plugin does not lint the files from child compiler

### Expected Behavior

plugin should have the same behaviour with previous loader

### How Do We Reproduce?

```
git clone https://github.com/wood1986/demo2

# loader scenario
git checkout loader
yarn
yarn run index 
# make some change index.node.js. it will lint

# plugin scenario
git checkout plugin
yarn
yarn run index
# make some change index.node.js. it will not lint

```

### PR DESCRIPTION
**Pull request by wood1986**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

fix #125

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Review by alexander-akait — DISMISSED** [review]
/cc @ricardogobbosouza

File: src/index.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ class ESLintWebpackPlugin {
     // Do not re-hook
     if (
       // @ts-ignore
-      compiler.hooks.thisCompilation.taps.find(({ name }) => name === this.key)
+      compiler.hooks.compilation.taps.find(({ name }) => name === this.key)
```
Comment (wood1986) [inline src/index.js:80]: @alexander-akait this also needs to change

**Comment by wood1986** [comment]
any updates?
